### ISSUE TITLE
Test all possible scenarios

### ISSUE THREAD

**Issue by Martouta** [Martouta/roar_responder#11]
This gem probably is gonna be done through TDD so I gotta add the tests! 🚨

What matters the most is the actual integration with Rails so it should be mostly integration tests.

DRY (and refactor in general) along the way.

#### Unit Tests

- [x] The gem version is present

##### Test 'representer_class' for the controller at an instance level (for each action)

- [x] 'respond_with' for a successful 'GET' request of an entity (Active Record) #12
- [x] 'respond_with' for a successful 'GET' request of a collection (ActiveRecord::Relation) #14 
- [x] 'respond_with' for a successful 'POST' request of an entity (Active Record) #15 
- [x] 'respond_with' for a failed 'POST' request of an entity (Active Record) #17
- [x] 'respond_with' for a successful 'GET' request of an entity (Mongo ID) #18
- [x] 'respond_with' for a successful 'GET' request of a collection (Mongoid::Criteria) #18
- [x] 'respond_with' for a successful 'POST' request of an entity (Mongo ID) #18
- [x] 'respond_with' for a failed 'POST' request of an entity (Mongo ID) #18
- [x] 'respond_with' for a successful 'GET' request of an entity (PORO) #19
- [x] 'respond_with' for a successful 'GET' request of a collection (Array of PORO) #19
- [x] 'respond_with' for a successful 'POST' request of an entity (PORO) #19
- [x] 'respond_with' for a failed 'POST' request of an entity (PORO) #19

Refactor in #20 

##### Test 'representer_class' for the controller at an class level (define representer_class for the class)

- [x] 'respond_with' for a successful 'GET' request of an entity (Active Record) #21
- [x] 'respond_with' for a successful 'GET' request of a collection (ActiveRecord::Relation) #21
- [x] 'respond_with' for a successful 'POST' request of an entity (Active Record) #21
- [x] 'respond_with' for a failed 'POST' request of an entity (Active Record) #21
- [x] 'respond_with' for a successful 'GET' request of an entity (Mongo ID) #21
- [x] 'respond_with' for a successful 'GET' request of a collection (Mongoid::Criteria) #21
- [x] 'respond_with' for a successful 'POST' request of an entity (Mongo ID) #21
- [x] 'respond_with' for a failed 'POST' request of an entity (Mongo ID) #21
- [x] 'respond_with' for a successful 'GET' request of an entity (PORO) #21
- [x] 'respond_with' for a successful 'GET' request of a collection (Array of PORO) #21
- [x] 'respond_with' for a successful 'POST' request of an entity (PORO) #21
- [x] 'respond_with' for a failed 'POST' request of an entity (PORO) #21
- [x] ⚠️ Ensure that it is not inferring the value but actual fetching it from the direct manual definition inside the controller

##### Test 'representer_class' for the controller being inferred for the model

- [x] 'respond_with' for a successful 'GET' request of an entity (Active Record) #27
- [x] 'respond_with' for a successful 'GET' request of a collection (ActiveRecord::Relation) #27
- [x] 'respond_with' for a successful 'POST' request of an entity (Active Record) #27
- [x] 'respond_with' for a failed 'POST' request of an entity (Active Record) #27
- [x] 'respond_with' for a successful 'GET' request of an entity (Mongo ID) #27
- [x] 'respond_with' for a successful 'GET' request of a collection (Mongoid::Criteria) #27
- [x] 'respond_with' for a successful 'POST' request of an entity (Mongo ID) #27
- [x] 'respond_with' for a failed 'POST' request of an entity (Mongo ID) #27
- [x] 'respond_with' for a successful 'GET' request of an entity (PORO) #23
- [x] 'respond_with' for a successful 'GET' request of a collection (A Ruby object that acts as a collection of DummyPoro and that responds to 'length' and other enumerable methods perhaps... because a bare Array wouldn't respond to model_name which is necessary here) #26 
- [x] 'respond_with' for a successful 'POST' request of an entity (PORO) #24 
- [x] 'respond_with' for a failed 'POST' request of an entity (PORO) #25 

Refactor in #28

##### Test render a model to JSON with default serializer
- [x] Test default model.to_json when the inferred representer class does not exist. The resource of this test also does not need to respond to `model_name`, but apparently, it needs to respond to `to_model` although that it's not for this gem itself but for one of the dependencies. #29

**Comment by Martouta** [comment]
✅
